#=============================================================================
# scripts/simulate_progression.R
# Grounded 30-Year Spatiotemporal Outbreak Projection & Video Generation
#=============================================================================

library(tidyverse)
library(terra)
library(sf)
library(ggplot2)
library(tidyterra)
library(gganimate)
library(ggspatial) # Required for formal GIS north arrow and scale bar elements
library(av)

#-----------------------------------------------------------------------------
# 1. Ingest Pipeline Spatial Assets & Parameters ----
#-----------------------------------------------------------------------------
if(!file.exists("outputs/nodes.rds") || !file.exists("outputs/distance_matrix.rds")) {
  stop("Missing structural inputs. Please run 'scripts/network_nodes.R' first.")
}
if(!file.exists("outputs/optimal_abc_parameters.rds")) {
  stop("Parameters uncalibrated. Please run 'scripts/ibm_smc_abc.R' first.")
}

# Load the empirical host landscape matrix generated by network_nodes.R
empirical_nodes <- readRDS("outputs/nodes.rds")
empirical_dist_matrix <- readRDS("outputs/distance_matrix.rds")

# Load ABC optimized parameter metrics
abc_params <- readRDS("outputs/optimal_abc_parameters.rds")
beta_val  <- abc_params %>% filter(parameter == "beta") %>% pull(optimal_value)
gamma_val <- abc_params %>% filter(parameter == "gamma_dist") %>% pull(optimal_value)

N_nodes <- nrow(empirical_nodes)
total_years <- 30

#-----------------------------------------------------------------------------
# 2. Map Field-Confirmed Points to the Host Landscape ----
#-----------------------------------------------------------------------------
cat(">>> Mapping field-confirmed epicenters to landscape nodes...\n")

true_positives <- dataEpi %>%
  filter(`EACMV-Ug` == "yes") %>%
  mutate(Longitude = as.numeric(Longitude), Latitude = as.numeric(Latitude)) %>%
  filter(!is.na(Longitude), !is.na(Latitude)) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
  st_transform(32630) # Project to UTM 30N metric coordinates

nodes_sf <- st_as_sf(empirical_nodes, coords = c("x", "y"), crs = 32630)
nearest_node_indices <- st_nearest_feature(true_positives, nodes_sf) %>% unique()

#-----------------------------------------------------------------------------
# 3. Execute Grounded Forward Projection Simulation ----
#-----------------------------------------------------------------------------
cat(">>> Running forward epidemic projection over host matrix...\n")

simulation_history <- vector("list", total_years)
status <- rep("Susceptible", N_nodes)
status[nearest_node_indices] <- "Infected"

simulation_history[[1]] <- empirical_nodes %>%
  mutate(Year = 1, Status = status)

for (year in 2:total_years) {
  current_infected <- which(status == "Infected")
  current_susceptible <- which(status == "Susceptible")
  
  if (length(current_infected) > 0 && length(current_susceptible) > 0) {
    escape_probabilities <- sapply(current_susceptible, function(s_idx) {
      distances <- empirical_dist_matrix[s_idx, current_infected]
      kernel <- beta_val / (1 + (distances / 1000)^gamma_val)
      prod(1 - kernel)
    })
    
    infection_risk <- 1 - escape_probabilities
    new_infections <- current_susceptible[runif(length(current_susceptible)) < infection_risk]
    
    if (length(new_infections) > 0) {
      status[new_infections] <- "Infected"
    }
  }
  
  simulation_history[[year]] <- empirical_nodes %>%
    mutate(Year = year, Status = status)
}

# CRITICAL FIX: To map a single continuous color metric that captures both suitability 
# and epidemiological status simultaneously, we create a continuous "display_value".
# Susceptible nodes map between [0 and 1] (based on risk metric).
# Infected nodes are shifted up to map between [2 and 3], creating a clean color break.
animation_df <- bind_rows(simulation_history) %>%
  mutate(
    risk_norm = (risk - min(risk)) / (max(risk) - min(risk)), # Normalizes risk to 0-1 range
    display_value = if_else(Status == "Susceptible", risk_norm, risk_norm + 2)
  )

#-----------------------------------------------------------------------------
# 4. Render Spatial Spatiotemporal Progression Animation ----
#-----------------------------------------------------------------------------
cat(">>> Compiling map visualization steps via gganimate...\n")
#=============================================================================
# Refined Cartographic Representation Configuration
#=============================================================================

anim_plot <- ggplot() +
  # Single clean layer rendering host landscape variations interactively
  geom_point(
    data = animation_df,
    aes(x = x, y = y, color = display_value, size = risk),
    alpha = 0.90
  ) +
  # Fixed bi-modal continuous gradient scaling engine
  # [0 to 1] maps cleanly to rich greens | [2 to 3] maps cleanly to stark outbreak reds
  scale_color_gradientn(
    colors = c("#edf8e9", "#bae4b3", "#74c476", "#238b45",  # Green palette (Susceptible)
               "#fee0d2", "#fc9272", "#ef3b2c", "#cb181d"), # Red palette (Infected)
    values = c(0.0, 0.15, 0.35, 0.50,                       # Relative placement inside [0-1]
               0.51, 0.65, 0.85, 1.0),                      # Relative placement inside [2-3]
    breaks = c(0.2, 0.8, 2.2, 2.8),
    labels = c("Sparse Host (S)", "Dense Patch (S)", "Initial Entry (I)", "Severe Outbreak (I)"),
    name = "Landscape Condition"
  ) +
  scale_size_continuous(range = c(1.2, 6.0), name = "Cassava Suitability Density") +
  
  # Add formal cartographic referencing elements
  annotation_north_arrow(
    location = "tl", which_north = "true",
    pad_x = unit(0.2, "in"), pad_y = unit(0.2, "in"),
    style = north_arrow_fancy_orienteering(fill = c("grey20", "white"))
  ) +
  annotation_scale(
    location = "bl", width_hint = 0.25,
    unit_category = "metric", style = "bar" # "bar" renders better than "ticks" at high resolution
  ) +
  
  theme_minimal(base_family = "sans") + # Enforces clean, anti-aliased font rendering
  labs(
    title = "West Africa: 30-Year Grounded CMD/UG Invasion Simulation",
    subtitle = "Year: {frame_time} of 30 | Green = Healthy Landscape Mosaic | Red = Pathogen Trajectory",
    x = "Easting (UTM 30N / Meters)",
    y = "Northing"
  ) +
  theme(
    plot.title = element_text(face = "bold", size = 16, color = "#1a1a1a"),
    plot.subtitle = element_text(size = 12, color = "grey20", margin = margin(b = 10)),
    legend.position = "right",
    legend.title = element_text(face = "bold", size = 10),
    panel.grid.major = element_line(color = "grey92", size = 0.25),
    panel.background = element_rect(fill = "#fafafa", color = NA) # Soft tint background to pop greens/reds
  ) +
  transition_time(Year) +
  ease_aes('linear')

cat(">>> Rendering video containers directly to output drive...\n")

#-----------------------------------------------------------------------------
# High-Quality Slow-Frame Video Rendering Configuration
#-----------------------------------------------------------------------------
animate(
  plot = anim_plot,
  nframes = total_years,
  fps = 1,                      # Change to 0.5 if you want it even slower (2 seconds per frame)
  res = 150,                    # CRITICAL: Increases rendering resolution to eliminate blur/pixelation
  width = 1200,                 # Expanded pixel resolution geometry bounds
  height = 850,
  renderer = av_renderer(file = "outputs/grounded_epidemic_progression_highres.mp4")
)

cat("✔ Finalized! Publication-grade trajectory video exported to 'outputs/grounded_epidemic_progression_highres.mp4'\n")